Mobile Navigation
upb-uc4/ui-web pull request #390
Opened 2020-08-21 09:18 UTC by theovier

# Description

Implements issue #284

## Reason for this PR
- Users want to smoothly navigate on our website even on mobile devices.

## Changes in this PR
- Add mobile navigation bar on smaller screen sizes.

## Type of change
- New feature

# How Has This Been Tested?

- [x] Manually tested all use cases this could alter

**Test Configuration**:
- OS: Windows Mac Linux
- Browser: Firefox Chrome Safari Chromium

- Frontend:
  - [x] Development build
- Backend:
  - [x] No backend needed to test this

# Checklist:

- [x] I added corresponding E2E tests
- [x] I have performed a self-review of my own code
- [x] My changes generate no new linting warnings or console warnings
- [x] I have updated the CHANGELOG.md to include any changes made in this PR

2020-08-24 12:01 UTC, bastihav approved these changes

2020-08-24 12:01 UTC, bastihav commented on src/components/navigation/navbar/mobile/common/profile/ProfileMenuBody.vue
> +    import Student from "../../../../../../api/api_models/user_management/Student";
```suggestion
    import Lecturer from "@/api/api_models/user_management/Lecturer";
    import Admin from "@/api/api_models/user_management/Admin";
    import Student from "@/api/api_models/user_management/Student";
```

2020-08-26 09:47 UTC, tobias-wiese approved these changes
looks fancy.
I would suggest 2 things: 
1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
2. If a user opens the burger menu for the first time, the submenus (e.g. ```My Profile```) are expanded by default. They should be collapsed at this point to provide a better overview.

2020-08-26 09:54 UTC, tobias-wiese requested changes
The menu points are not aligned properly

![grafik](https://user-images.githubusercontent.com/63233799/91289615-dd2a4d80-e792-11ea-881b-0874ad1c75e4.png)

2020-08-26 16:44 UTC, theovier commented
> The menu points are not aligned properly
> 
> ![grafik](https://user-images.githubusercontent.com/63233799/91289615-dd2a4d80-e792-11ea-881b-0874ad1c75e4.png)

Can you provide context? When does this happen? I never experienced this.

2020-08-26 16:48 UTC, theovier commented
> looks fancy.
> I would suggest 2 things:
> 
> 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.

Acknowledged. 
1) I am unsure what the normal procedure would be here since I might end up on the wrong subsite and want to navigate fast to another section which I actually searched for. However, if @bastihav feels the same, we can collapse the burger menu on route change.
2) This was done purposely to show all the options a user has since we do not have really many submenus altogether. Again, this might be preference so I don't have a problem changing it.

2020-08-26 16:49 UTC, tobias-wiese commented
> 
> 
> > The menu points are not aligned properly
> > ![grafik](https://user-images.githubusercontent.com/63233799/91289615-dd2a4d80-e792-11ea-881b-0874ad1c75e4.png)
> 
> Can you provide context? When does this happen?

This seem to happen in firefox only, at any screensize where the burger menu is shown

2020-08-26 16:50 UTC, theovier commented
> > > The menu points are not aligned properly
> > > ![grafik](https://user-images.githubusercontent.com/63233799/91289615-dd2a4d80-e792-11ea-881b-0874ad1c75e4.png)
> > 
> > 
> > Can you provide context? When does this happen?
> 
> This seem to happen in firefox only, at any screensize where the burger menu is shown

I will look into this.

2020-08-26 16:52 UTC, bastihav commented
> > looks fancy.
> > I would suggest 2 things:
> > 
> > 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> > 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.
> 
> Acknowledged.
> 
> 1. I am unsure what the normal procedure would be here since I might end up on the wrong subsite and want to navigate fast to another section which I actually searched for. However, if @bastihav feels the same, we can collapse the burger menu on route change.

I think closing the menu is the normal procedure, I just checked a couple of websites, none of which kept the menu open.

> 2. This was done purposely to show all the options a user has since we do not have really many submenus altogether. Again, this might be preference so I don't have a problem changing it.

I agree that we do not have many submenus at this moment, but if we are showing all options by default, we would not need sub menus at all. The point of sub menus is, that you organize menu points and "make the UI a bit more organized", so I would  agree with Tobi here.

2020-08-26 17:51 UTC, theovier commented
> looks fancy.
> I would suggest 2 things:
> 
> 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.

2. is implemented by af20774. 

1. seems to pose some problems as I was unable to use the route guards in the mobile base navbar component. Will have to look further into this as it seems not to be as easy as assumed.

2020-08-26 18:57 UTC, tobias-wiese commented
> 
> 
> > looks fancy.
> > I would suggest 2 things:
> > 
> > 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> > 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.
> 
>     1. seems to pose some problems as I was unable to use the route guards in the mobile base navbar component. Will have to look further into this as it seems not to be as easy as assumed.
> 
>     2. is implemented by [af20774](https://github.com/upb-uc4/ui-web/commit/af2077412d7a401aaca6e6595d993580d60d14e6).

**To 1:**
I think the problem is, that you cannot call a navigation guard out of a component, that is not the routed component (declared in router). I had this problem, too. As the navbar is a component, that is not part of the routing structure, I do not believe that we can use navigation guards for this purpose. We may implement a function
```
function navigate(target: string) {
    isOpen.value = false;
    Router.push(target);
}
````
that is then called by each navbar item. Not pretty, but it should do the job.

2020-08-27 06:06 UTC, theovier commented
> > > looks fancy.
> > > I would suggest 2 things:
> > > 
> > > 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> > > 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.
> > 
> > 
> > ```
> > 1. seems to pose some problems as I was unable to use the route guards in the mobile base navbar component. Will have to look further into this as it seems not to be as easy as assumed.
> > 
> > 2. is implemented by [af20774](https://github.com/upb-uc4/ui-web/commit/af2077412d7a401aaca6e6595d993580d60d14e6).
> > ```
> 
> **To 1:**
> I think the problem is, that you cannot call a navigation guard out of a component, that is not the routed component (declared in router). I had this problem, too. As the navbar is a component, that is not part of the routing structure, I do not believe that we can use navigation guards for this purpose. We may implement a function
> 
> ```
> function navigate(target: string) {
>     isOpen.value = false;
>     Router.push(target);
> }
> ```
> 
> that is then called by each navbar item. Not pretty, but it should do the job.

You are correct, that was the issue I also assumed. However, calling this in the `menuItems` is not a solution as they are children of children of children of the navbar. We would have to emit several levels in order to achieve this. Might look into using the store for this. However, I don't like any of the solutions to be honest.

2020-08-27 12:58 UTC, tobias-wiese commented
> 
> 
> > > > looks fancy.
> > > > I would suggest 2 things:
> > > > 
> > > > 1. If one navigates via the burger menu, I'd expect the burger menu to close when the target route is reached.
> > > > 2. If a user opens the burger menu for the first time, the submenus (e.g. `My Profile`) are expanded by default. They should be collapsed at this point to provide a better overview.
> > > 
> > > 
> > > ```
> > > 1. seems to pose some problems as I was unable to use the route guards in the mobile base navbar component. Will have to look further into this as it seems not to be as easy as assumed.
> > > 
> > > 2. is implemented by [af20774](https://github.com/upb-uc4/ui-web/commit/af2077412d7a401aaca6e6595d993580d60d14e6).
> > > ```
> > 
> > 
> > **To 1:**
> > I think the problem is, that you cannot call a navigation guard out of a component, that is not the routed component (declared in router). I had this problem, too. As the navbar is a component, that is not part of the routing structure, I do not believe that we can use navigation guards for this purpose. We may implement a function
> > ```
> > function navigate(target: string) {
> >     isOpen.value = false;
> >     Router.push(target);
> > }
> > ```
> > 
> > 
> > that is then called by each navbar item. Not pretty, but it should do the job.
> 
> You are correct, that was the issue I also assumed. However, calling this in the `menuItems` is not a solution as they are children of children of children of the navbar. We would have to emit several levels in order to achieve this. Might look into using the store for this. However, I don't like any of the solutions to be honest.

We could add an issue for ```1``` and merge this feature if we do not find a solution until tomorrow, as it is technically complete.

2020-08-27 13:04 UTC, tobias-wiese approved these changes
As the wrong margins are corrected, I will approve this. If you want, you can merge the branch without fixing the collapsing of the burger menu, but we should catch up this asap then :)

2020-08-27 13:58 UTC, merged