Feature/configuration management
upb-uc4/ui-web pull request #755
Opened 2020-12-03 15:31 UTC by bastihav

---------------------------------------------
Remove this, if this PR is not to main!

<b>Version to release: v0.7.0</b>

## Merging this pull request will automatically:
- create a tag using the version in our package.json
- publish a release using this tag, referencing the CHANGELOG.md
- publish the release on dockerhub using the version of our package.json

## Please fill out the following checklist:
- [ ] The version of the package.json is different to every other tag in this repository
- [ ] The CHANGELOG.md contains all changes (bugfixes, features, dependency updates, ...) for this release
----------------------------

# Description

- Fixes #XXX (for bugfixes)
- Closes #XXX (for feature implementation)

## Reason for this PR
- [INSERT REASONS HERE]

## Changes in this PR
- [INSERT CHANGES HERE]

### Dependency update
- List all new dependencies (delete if no additions)

## Type of change (remove all that don't apply)
- Refactoring
- Bug fix (non-breaking change which fixes an issue)
- Hotfix
- New feature (non-breaking change which adds functionality)
- Testing
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update (README, e.g. deployment changes)
  - I added the documentation
# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manually tested all use cases this could alter

**Test Configuration**:
- OS: Windows Mac Linux
- Browser: Firefox Chrome Safari Chromium

- Frontend: (remove all that don't apply)
  - [ ] Development build
  - [ ] Production build
  - [ ] Dockerized production build
- Backend: (remove all that don't apply)
  - [ ] No backend needed to test this
  - [ ] deployed production build
  - [ ] deployed development build
  - [ ] deployed experimental build
  - [ ] Local build (commit hash [XXXXXXX])

# Checklist: (remove all that don't apply)

- [ ] I added corresponding E2E tests (especially for bugfixes)
- [ ] I added corresponding unit tests (if API code)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new linting warnings or console warnings
- [ ] I have updated the package.json version if this is a new release candidate (remove is it is not)
- [ ] I have updated the CHANGELOG.md to include any changes made in this PR (add WIP to the top, if there is none already)

2020-12-04 14:56 UTC, bastihav commented
![image](https://user-images.githubusercontent.com/8998495/101176685-1ce0bb00-3647-11eb-917a-251beea8f816.png)

the merge introduced some ugly styling

2020-12-04 15:15 UTC, tobias-wiese commented
> 
> 
> ![image](https://user-images.githubusercontent.com/8998495/101176685-1ce0bb00-3647-11eb-917a-251beea8f816.png)
> 
> the merge introduced some ugly styling

this should be fixed

2020-12-08 12:36 UTC, tobias-wiese requested changes
Overall that is great work. 
For the E2E we should propagate the id from the parent component into the base-input component for properly getting them via Cypress. Otherwise, it looks like the following:
![grafik](https://user-images.githubusercontent.com/63233799/101484385-d1d1eb00-3959-11eb-9510-d360f1254520.png)

I would suggest something like
In the parent:
`<base-input identifier="WhatEverIdYouWant" ..../>`
and stting the input field's id via the prop in the `BaseInput.vue`
`<input :id="identifier" .../>`

Additionally we must not forget to rework the error message assertation in the E2E tests

2020-12-08 12:40 UTC, tobias-wiese commented
Consider closing #354 on merge (or connecting it)

2020-12-11 21:52 UTC, tobias-wiese commented
> 
> 
> Overall that is great work.
> For the E2E we should propagate the id from the parent component into the base-input component for properly getting them via Cypress. Otherwise, it looks like the following:
> ![grafik](https://user-images.githubusercontent.com/63233799/101484385-d1d1eb00-3959-11eb-9510-d360f1254520.png)
> 
> I would suggest something like
> In the parent:
> `<base-input identifier="WhatEverIdYouWant" ..../>`
> and stting the input field's id via the prop in the `BaseInput.vue`
> `<input :id="identifier" .../>`
> 
> Additionally we must not forget to rework the error message assertation in the E2E tests

should be fixed now

2020-12-11 21:52 UTC, tobias-wiese approved these changes

2021-01-06 15:07 UTC, merged