Release v0.15.0
upb-uc4/ui-web pull request #779
Opened 2020-12-18 16:18 UTC by tobias-wiese

Remove this, if this PR is not to main!

<b>Version to release: v0.15.0</b>

## Merging this pull request will automatically:
- create a tag using the version in our package.json
- publish a release using this tag, referencing the CHANGELOG.md
- publish the release on dockerhub using the version of our package.json

## Please fill out the following checklist:
- [x] The version of the package.json is different to every other tag in this repository
- [x] The CHANGELOG.md contains all changes (bugfixes, features, dependency updates, ...) for this release

2020-12-18 16:21 UTC, theovier requested changes

2020-12-18 16:21 UTC, theovier commented on CHANGELOG.md
> +# [0.15.1](https://github.com/upb-uc4/ui-web/compare/v0.14.0...v0.15.0) (2020-12-18)
```suggestion
# [0.15.0](https://github.com/upb-uc4/ui-web/compare/v0.14.0...v0.15.0) (2020-12-18)
```

2020-12-18 16:23 UTC, theovier approved these changes

2020-12-18 16:33 UTC, bastihav approved these changes

2020-12-22 10:46 UTC, this-kramer approved these changes

2020-12-22 16:02 UTC, nklsd approved these changes

2020-12-22 16:05 UTC, merged